site_name: Sistemes operatius monolloc 21-22
site_url: https://fpieseljust.github.io/som21-22/
docs_dir: 'md'
site_dir: 'docs'
nav:
    - Home: index.md
    - Unitats:
      - Unitat 3 - Gestió de la informació:
        - Teoria: unitats/ud3-info/comandaments.md
      - Unitat 4 - Usuaris, grups i permissos:
        - Teoria: unitats/ud4-permisos/UD4_SOM.md
        - Exercicis: unitats/ud4-permisos/UD4_SOM_exercicis.md
      - Unitat 5 - Processos i aplicacions:
        - Teoria: unitats/ud5-processos/UD5_SOM.md
    - About: about.md
theme:
  name: material
