site_name: Sistemes operatius monolloc 21-22
site_url: https://fpieseljust.github.io/som21-22/
docs_dir: 'md'
site_dir: 'docs'
nav:
    - Home: index.md
    - Unitats:
      - Unitat 3 - Gestió de la informació:
        - Comandaments: unitats/ud3-info/comandaments.md
    - About: about.md
theme:
  name: material
